#ifndef SHADER_DECLARATION_UTIL
#define SHADER_DECLARATION_UTIL

#define DECLARE_RESOURCE_DX(x, IDENTITY) x : IDENTITY
#define DECLARE_RESOURCE_VULKAN(x, IDENTITY) IDENTITY x

#ifndef DX_SHADER
#define DX_SHADER 1
#endif

#if DX_SHADER
#define DECLARE_RESOURCE(x, IDENTITY) DECLARE_RESOURCE_DX(x, IDENTITY)
#else
#define DECLARE_RESOURCE(x, IDENTITY) DECLARE_RESOURCE_VULKAN(x, IDENTITY)
#endif

#endif