#ifndef SHADER_DECLARATION_UTIL
#define SHADER_DECLARATION_UTIL

#define DECLARE_RESOURCE_DX(x, IDENTITY) x : IDENTITY
#define DECLARE_RESOURCE_VULKAN(x, IDENTITY) IDENTITY x

#define DECLARE_ATTRIBUTE_LOCATION_DX(x, IDENTITY) x : IDENTITY 
#define DECLARE_ATTRIBUTE_LOCATION_VULKAN(x, IDENTITY) IDENTITY x

#if DX_SHADER
#define DECLARE_RESOURCE(x, IDENTITY) DECLARE_RESOURCE_DX(x, IDENTITY)
#define DECLARE_ATTRIBUTE_LOCATION(x, IDENTITY) DECLARE_ATTRIBUTE_LOCATION_DX(x, IDENTITY)
#else
#define DECLARE_RESOURCE(x, IDENTITY) DECLARE_RESOURCE_VULKAN(x, IDENTITY)
#define DECLARE_ATTRIBUTE_LOCATION(x, IDENTITY) DECLARE_ATTRIBUTE_LOCATION_VULKAN(x, IDENTITY##_VK) : IDENTITY
#endif

#endif